name: Copy Release Archives

on:
  push:
    branches:
      - main

jobs:
  copy_archives:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Release Archives from Repl.it
      run: npx repl.it download

    - name: Move Release Archives to GitHub Workspace
      run: mv /home/runner/SClocalisationBot/release/* $GITHUB_WORKSPACE/release/

    - name: Commit and Push Changes
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update release archives"
        git push
